services:
  aspiresync:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    networks:
      - app-net
      - aspire-net
    volumes:
      - .:/opt/aspiresync
    # entrypoint: ['/opt/aspiresync/bin/aspiresync']  # good for prod, annoying in dev
    tty: true   # keeps the container running

networks:
  app-net: ~
  aspire-net:
    external: true
