services:
  webapp:
    build:
      context: .
      dockerfile: docker/webapp/Dockerfile
      target: dev
    environment:
      ASPIRECLOUD_ADMIN_API_URL: ${ASPIRECLOUD_ADMIN_API_URL}
      ASPIRECLOUD_ADMIN_API_KEY: ${ASPIRECLOUD_ADMIN_API_KEY}
    volumes:
      - .:/app
    networks:
      traefik: ~
      app-net: ~
      aspire-net:
        aliases:
          - 'sync.aspiredev.org'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aspiresync.rule=Host(`sync.aspiredev.org`)"
      - "traefik.http.routers.aspiresync-https.rule=Host(`sync.aspiredev.org`)"
      - "traefik.http.routers.aspiresync-https.tls=true"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/opt/pgdata
      - POSTGRES_DB=aspiresync
    volumes:
      - pgdata:/opt/pgdata
    networks:
      app-net: ~
      aspire-net:
        aliases:
          - 'db.sync.aspiredev.org'

networks:
  app-net: ~
  aspire-net:
    external: true
  traefik:
    external: true

volumes:
  pgdata: ~
