#!/usr/bin/env php
<?php

use AssetGrabber\Commands\Plugins\InternalPluginDownloadCommand;
use AssetGrabber\Commands\Plugins\DownlloadPluginsCommand;
use AssetGrabber\Commands\Plugins\MetaImportPluginsCommand;
use AssetGrabber\Commands\Plugins\MetaDownloadPluginsCommand;
use AssetGrabber\Commands\Plugins\DownloadPluginsPartialCommand;
use AssetGrabber\Commands\Themes\ThemeImportMetaCommand;
use AssetGrabber\Commands\Themes\ThemesMetaCommand;
use AssetGrabber\Commands\UtilCleanDataCommand;
use AssetGrabber\Commands\UtilUploadCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$config = require './config/config.php';

ini_set('memory_limit', '4G');

$dependencies                       = $config['dependencies'];
$dependencies['services']['config'] = $config;

$container = new \Laminas\ServiceManager\ServiceManager($dependencies);

$application = new Application();

$application->add($container->get(InternalPluginDownloadCommand::class));
$application->add($container->get(DownlloadPluginsCommand::class));
$application->add($container->get(MetaImportPluginsCommand::class));
$application->add($container->get(MetaDownloadPluginsCommand::class));
$application->add($container->get(DownloadPluginsPartialCommand::class));

$application->add($container->get(ThemesMetaCommand::class));
$application->add($container->get(ThemeImportMetaCommand::class));

$application->add($container->get(UtilCleanDataCommand::class));
$application->add($container->get(UtilUploadCommand::class));

$application->run();
