#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$config = require './config/config.php';

ini_set('memory_limit', '4G');

$dependencies                       = $config['dependencies'];
$dependencies['services']['config'] = $config;

$container = new \Laminas\ServiceManager\ServiceManager($dependencies);

$application = new Application();

$application->add($container->get(\AssetGrabber\Commands\Plugins\InternalPluginDownloadCommand::class));
$application->add($container->get(\AssetGrabber\Commands\Plugins\PluginsGrabCommand::class));
$application->add($container->get(\AssetGrabber\Commands\Plugins\PluginsImportMetaCommand::class));
$application->add($container->get(\AssetGrabber\Commands\Plugins\PluginsMetaCommand::class));
$application->add($container->get(\AssetGrabber\Commands\Plugins\PluginsPartialCommand::class));

$application->add($container->get(\AssetGrabber\Commands\UtilCleanDataCommand::class));
$application->add($container->get(\AssetGrabber\Commands\UtilUploadCommand::class));

$application->run();
