#!/usr/bin/env php
<?php

use AssetGrabber\Commands\Plugins\InternalPluginDownloadCommand;
use AssetGrabber\Commands\Plugins\DownloadPluginsCommand;
use AssetGrabber\Commands\Plugins\MetaImportPluginsCommand;
use AssetGrabber\Commands\Plugins\MetaDownloadPluginsCommand;
use AssetGrabber\Commands\Plugins\DownloadPluginsPartialCommand;
use AssetGrabber\Commands\Themes\DownloadThemesCommand;
use AssetGrabber\Commands\Themes\DownloadThemesPartialCommand;
use AssetGrabber\Commands\Themes\InternalThemeDownloadCommand;
use AssetGrabber\Commands\Themes\MetaImportThemesCommand;
use AssetGrabber\Commands\Themes\MetaDownloadThemesCommand;
use AssetGrabber\Commands\UtilCleanCommand;
use AssetGrabber\Commands\UtilUploadCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$config = require './config/config.php';

ini_set('memory_limit', '4G');

$dependencies                       = $config['dependencies'];
$dependencies['services']['config'] = $config;

$container = new \Laminas\ServiceManager\ServiceManager($dependencies);

$application = new Application();

$application->add($container->get(InternalPluginDownloadCommand::class));
$application->add($container->get(DownloadPluginsCommand::class));
$application->add($container->get(MetaImportPluginsCommand::class));
$application->add($container->get(MetaDownloadPluginsCommand::class));
$application->add($container->get(DownloadPluginsPartialCommand::class));

$application->add($container->get(MetaDownloadThemesCommand::class));
$application->add($container->get(MetaImportThemesCommand::class));
$application->add($container->get(DownloadThemesCommand::class));
$application->add($container->get(DownloadThemesPartialCommand::class));
$application->add($container->get(InternalThemeDownloadCommand::class));

$application->add($container->get(UtilCleanCommand::class));
$application->add($container->get(UtilUploadCommand::class));
$application->run();
