#!/usr/bin/env php
<?php

use AssetGrabber\Services\PluginDownloadService;
use AssetGrabber\Services\PluginListService;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$application = new Application();
$application->add(new \AssetGrabber\Commands\GrabPluginsCommand(new PluginListService(), new PluginDownloadService()));
$application->add(new \AssetGrabber\Commands\DownloadPluginVersionsCommand(new PluginListService(), new PluginDownloadService()));
$application->run();